#!/usr/bin/env bash
# Script to display information about subdomains.

subdomains=("www" "lb-01" "web-01" "web-02")
if (("$#"==1))
then
    for subdomain in "${subdomains[@]}"
    do
        record_type=$(dig "$subdomain"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
        destination=$(dig "$subdomain"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    done
elif (("$#"==2))
then
    record_type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
    destination=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $record_type record and points to $destination"
fi
