#!/usr/bin/env bash
# Script to transfer a file from a client to a server

FILEPATH=$1 
USERIP=$2 
USER=$3
PATHSSH=$4

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

fi
scp -i "$PATHSSH" -o StrictHostKeyChecking=no "$FILEPATH" "$USER"@"$USERIP":~/
