#!/usr/bin/env bash
# Script that make Nginx to run, and listen port 80 of all the server’s active IPv4 IPs
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/ipv6only=on/ /" /etc/nginx/sites-enabled/default
sudo service nginx restart
