#!/usr/bin/env bash
# script that creates a file with PID &
# Displays messages according to receiving signal
on_SIGINT () {
echo "Y U no love me?!"
  exit
}
on_SIGTERM () {
    echo "I hate the kill command"
    rm /var/run/my.pid
    exit
}
on_SIGQUIT () {
    rm /var/run/my.pid
    exit
}

echo $$ > /var/run/myscript.pid
trap on_SIGTERM SIGTERM
trap on_SIGQUIT SIGQUIT
trap on_SIGINT SIGINT

while (( 1 ))
do
    echo To infinity and beyond
    sleep 2
done
